name: ✨ 기능 추가 (feat)
about: 새로운 기능 또는 개선 사항 요청
title: "[feat] "
labels: ["feat"]
body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 변경/추가하고 싶은 기능을 설명해주세요.
      placeholder: "사용자 시나리오, 기대 효과 등"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 구현 / 아이디어
      description: 세부 구현 계획이나 참고 링크가 있다면 적어주세요.
      placeholder: "-"
